version: "3.9"

services:
  db:
    image: postgres:15
    container_name: kaspi-parser-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # значения берутся из .env, здесь оставлены дефолты для ясности
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-app_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  app:
    build: .
    container_name: kaspi-parser-app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: ["/bin/sh", "/app/entrypoint.sh"]
    restart: unless-stopped

volumes:
  postgres_data:
